version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: pwd
      - run: ls -l
      - run: cat README.md
      - run: yarn install
      - run: yarn test
